# Generated by Django 3.2.22 on 2023-10-29 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_stock_stockrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stock')),
            ],
            options={
                'verbose_name': 'StockRequest',
                'verbose_name_plural': 'StockRequests',
            },
        ),
        migrations.DeleteModel(
            name='StockRequest',
        ),
    ]
