# Generated by Django 3.2.22 on 2023-10-29 00:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20231029_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='product',
            new_name='item',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='quantity',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockitem',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.requeststock'),
            preserve_default=False,
        ),
    ]
