# Generated by Django 3.2.22 on 2023-10-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_ordercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='threshold',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
