# Generated by Django 3.2.22 on 2023-10-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_stock_reorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_product',
            field=models.BooleanField(default=True),
        ),
    ]
